ecommerce/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/categories', [CategoryController::class, 'index'])->name('category.index');
Route::get('/categories/create', [CategoryController::class, 'create']);
Route::post('/categories/store', [CategoryController::class, 'store']);
Route::get('/categories/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');
Route::put('/categories/update/{id}', [CategoryController::class, 'update'])->name('category.update');
Route::delete('/categories/delete/{id}', [CategoryController::class, 'destroy'])->name('category.delete');
Route::delete('/categories/ajax_delete', [CategoryController::class, 'ajax_destroy'])->name('category.ajax_delete');

Route::get('/contact', [ContactController::class, 'contact_form'])->name('contact.form');
Route::post('/contact/send_mail', [ContactController::class, 'send_mail']);
Route::resource('product', ProductController::class);
Route::delete('/product/delete', [CategoryController::class, 'destroy'])->name('product.delete');


//Route::get('/template', [TemplateController::class, 'index'])->name('template.index');
//Route::get('/template/elements', [TemplateController::class, 'elements'])->name('template.elements');
//Route::get('/template/generic', [TemplateController::class, 'generic'])->name('template.generic');

ecommerce/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
        'description',
        'category_id',
        'price',
        'image'
    ];

    public function category()
	{
	    return $this->belongsTo(Category::class);
	}
}

ecommerce/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;

use Illuminate\Support\Str;
use File;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::all();
        return view('Product.index',compact('products'));
    }

    public function create()
	{
	    $categories = Category::all();
	    return view('Product.create', compact('categories'));
	}

	public function store(Request $request)
	{
	    $this->validate($request, [
	        'name' => 'required|string|max:100',
	        'description' => 'required',
	        'category_id' => 'required|exists:categories,id',
	        'price' => 'required',
	        'image' => 'required|image|mimes:png,jpeg,jpg'
	    ]);

	    if ($request->hasFile('image')) {
	        $file = $request->file('image');
	        $filename = time() . Str::slug($request->name) . '.' . $file->getClientOriginalExtension();
	        $file->storeAs('public/products', $filename);

	        /*$product = Product::create([
	            'name' => $request->name,
				'description' => $request->description,
	            'category_id' => $request->category_id,
	            'price' => $request->price,
				'image' => $filename,
	        ]);*/

			$new_product = new Product;
			$new_product->name = $request->name;
			$new_product->description = $request->description;
			$new_product->category_id = $request->category_id;
			$new_product->price  = $request->price;
			$new_product->image  = $filename;
			$new_product->save();
	        return redirect(route('product.index'))->with('alert', 'added product');
	    }
	}

	public function edit($id)
	{
	    $product = Product::findOrfail($id);
	    $categories = Category::all();
	    return view('Product.edit', compact('product', 'categories'));
	}

	public function update(Request $request, $id)
	{
	    $this->validate($request, [
	        'name' => 'required|string|max:100',
	        'description' => 'required',
	        'category_id' => 'required|exists:categories,id',
	        'price' => 'required',
	        'image' => 'required|image|mimes:png,jpeg,jpg'
	    ]);

	    $product = Product::findOrfail($id);
	    $filename = $product->image;
	  
	    if ($request->hasFile('image')) {
	        $file = $request->file('image');
	        $filename = time() . Str::slug($request->name) . '.' . $file->getClientOriginalExtension();
	        $file->storeAs('public/products', $filename);
	        File::delete(storage_path('app/public/products/' . $product->image));
	    }
		
	    /*$product->update([
	        'name' => $request->name,
			'description' => $request->description,
			'category_id' => $request->category_id,
			'price' => $request->price,
			'image' => $filename,
	    ]);*/

		$product->name = $request->name;
		$product->description = $request->description;
		$product->category_id = $request->category_id;
		$product->price  = $request->price;
		$product->image  = $filename;
		$product->save();


	    return back()->with('alert', 'Product updated successfully');
	}

	/*public function destroy($id)
	{
	    $product = Product::find($id);
	    File::delete(storage_path('app/public/products/' . $product->image));
	    $product->delete();
	    return redirect(route('product.index'))->with(['success' => 'Product Has Been Removed']);
	}*/

	public function destroy(Request $request)
	{
	    if($request->ajax()){
            $product = Product::findOrfail($request->product_id);
			File::delete(storage_path('app/public/products/' . $product->image));
            $product->delete();
            return response()->json(["mensaje"=>"borrado"]);
        }
	}

}

ecommerce/resources/views/Product/create.blade.php
@extends('Layouts.main_template')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <span>Add new product</span>
                    <a href="/product" class="btn btn-primary btn-sm">Back to product list</a>
                </div>
                <div class="card-body">   
                  @if ( session('alert') )
                    <div class="alert alert-success">{{ session('alert') }}</div>
                  @endif
                  <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @error('name')
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Name is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @enderror @if ($errors->has('description'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Description is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif

                    @if ($errors->has('category_id'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Category is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif

                    @if ($errors->has('price'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Price is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif

                    @if ($errors->has('image'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Image is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif
                    <input type="text" name="name" placeHolder="Name" class="form-control mb-2" value="{{ old('name') }}">
                    <input type="text" name="description" placeHolder="Description" class="form-control mb-2" value="{{ old('description') }}">
                    <label for="category_id">Category</label>
                    <select name="category_id" class="form-control mb-2">
                        <option value="">Select</option>
                        @foreach ($categories as $row)
                        <option value="{{ $row->id }}" {{ old('category_id') == $row->id ? 'selected':'' }}>{{ $row->name }}</option>
                        @endforeach
                    </select>
                    <input type="text" name="price" placeHolder="Price" class="form-control mb-2" value="{{ old('price') }}">
                    <label for="image">Product Image</label>
                    <input type="file" name="image" class="form-control mb-2" value="{{ old('image') }}">
                    <button class="btn btn-primary btn-block" type="submit">Add</button>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

ecommerce/resources/views/Product/edit.blade.php
@extends('Layouts.main_template')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <span>Update Product Information: {{$product->name}}</span>
                    <a href="/product" class="btn btn-primary btn-sm">Back to product list</a>
                </div>
                <div class="card-body">   
                  @if ( session('alert') )
                    <div class="alert alert-success">{{ session('alert') }}</div>
                  @endif
                  <form action="{{ route('product.update', $product->id) }}" method="post" enctype="multipart/form-data" >
                    @method('PUT')
                    @csrf
                    @error('name')
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Name is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @enderror @if ($errors->has('description'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Description is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif

                    @if ($errors->has('category_id'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Category is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif

                    @if ($errors->has('price'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Price is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif

                    @if ($errors->has('image'))
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        Image is required
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endif
                    <input type="text" name="name" placeHolder="Name" class="form-control mb-2" value="{{$product->name}}">
                    <input type="text" name="description" placeHolder="Description" class="form-control mb-2" value="{{$product->description}}">
                    <label for="category_id">Category</label>
                    <select name="category_id" class="form-control">
                        <option value="">Select</option>
                        @foreach ($categories as $row)
                        <option value="{{ $row->id }}" {{ $product->category_id == $row->id ? 'selected':'' }}>{{ $row->name }}</option>
                        @endforeach
                    </select>
                    <input type="text" name="price" placeHolder="Price" class="form-control mb-2" value="{{ $product->price }}">
                    <label for="image">Product Image</label>
                    <br>
                    <img src="{{ asset('storage/products/' . $product->image) }}" width="100px" height="100px" alt="{{ $product->name }}">
                    <hr>
                    <input type="file" name="image" class="form-control">
                    <p><strong>Leave it blank if you don't want to change the image</strong></p>
                    <button class="btn btn-primary btn-block" type="submit">Update</button>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

ecommerce/resources/views/Product/index.blade.php
@extends('Layouts.main_template')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-4">Products</h1>
            <p>{{date('l jS \of F Y h:i:s A')}}</p>
            <a href="/product/create" class="btn btn-primary">Add a new product</a>
            <div class="card-body">
                @if ( session('alert') )
                <div class="alert alert-success">{{ session('alert') }}</div>
                @endif
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">#id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Category</th>
                        <th scope="col">Price</th>
                        <th scope="col">Image</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $product)
                        <tr id="product_{{$product->id}}">
                        <td scope="row">{{$product->id}}</td>
                        <td scope="row">{{$product->name}}</td>
                        <td scope="row">{{$product->description}}</td>
                        <td scope="row">{{$product->category->name}}</td>
                        <td scope="row">{{$product->price}}</td>
                        <td scope="row">
                            <img src="{{ asset('storage/products/' . $product->image) }}" width="100px" height="100px" alt="{{ $product->name }}">
                        </td>
                        <td>
                            <a href="{{route('product.edit',$product)}}" class="btn btn-warning btn-sm">Edit</a>
                            <button type="submit" class="btn btn-danger btn-sm" value="{{$product->id}}" OnClick='delete_product(this);'>Delete</button>
                        </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js_code')

<script type = "text/javascript">

function delete_product(btn){
    var route = "{{ route('product.delete') }}"
    var token = $('meta[name="csrf-token"]').attr('content');
    
    $.ajax({
        url: route,
        headers: {'X-CSRF-TOKEN':token},
        type: "DELETE",
        data: {product_id: btn.value},
        dataType: 'json',
        success: function(response) {
                    console.log("Elemento " +  btn.value + " eliminado")
                    $('#product_'+btn.value).fadeOut("slow");
                }
    });
}

</script>

@endsection